language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: travis-heroku-2
  on: master
  skip_cleanup: true
  api_key:
	secure: Kv1rH9eC2jUF+KfSU8rKozXpqMWN+J7mHDew15xQNlQ0gkC8M9RqQO8MxiRnc9WIhZXh+o0b0RpElrn/F/wUQ+Mo17dHVSZKpzFQM822rZkodM7Jjo9I0PuO2REJDnUZC/wN88p1yWujq+VJVBsv6xQbXkYBCQ6qVE/FKwJsX6Q5asHX8+NgIt+1p/SeS9c0pJR223GCEnUCuQktlgLdf5IVpGvHDTTZF9Ree2E+navleJVdZUpteNmG+DINeMoBoAM2ygsW5hPcjrDI+TwMA+i+pJuXGUbUCB6xd6xmXGFi9Vk2rtE6kzvaR0uruQfGB5WMky3QqU1QdyFttiYF4BLHSIfHZolSbbebTSPGFcrLSbH++ek8+z8J/c1MO2nhboH7/s7sXGkJpDzIpRhovmlY0gGYOdUG5VR50pzy2WH8u66t3B/YMFEHXoSIBqqVbBL+1t2toG66vlm+zbLiFHuNCZDi0oac42z6twLk0akMAmoNaXUulFc+gRAdKLR5D3Qhm9U3Qd0SiNdVM9l3/JjtJxRgJOaei5v3mfLhHVCVbqyqiX7DJoj0K2tdqVJXqaMRp/qJYUMEyN96oTB01QOxGoQrR8KMZVUv2nR53Teq0FG4vBoarbZfWOUZBFcRI9SDVZcFgZ9pK1Us+Rw2510F23XYP0B2WLf66BtYxZ0=
